name: Concat Circles

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: "pandoc /home/runner/work/Pandemonium_Strats/Pandemonium_Strats/*.md > markdown_book.html" # gets appended to pandoc command
